#!/usr/bin/python

import numpy as np
import matplotlib.pyplot as plt
import re

models = ["pcs", "epidemic", "traffic"];
comm_models = ["multiple", "serialized", "funnelled", "single"];
warped_data_path = "."

def filenames(comm_model):
    wt = 0;
    if comm_model == "single":
        wt = 1;
    else:
        wt = 7;

    for n in [1, 2, 4, 8]:
        filename = "{}n{}wt{}sq25ssp1000gvtp_pg.csv".format(n, wt, wt)
        yield filename

def filter_total_lines(f):
    for line in f:
        if "Total" in line:
            yield line

def addPlotXY(plots, title, xlab, ylab, lines):
    new_plot = {"title": title, "xlabel": xlab, "ylabel": ylab, "lines": lines}
    plots.append(new_plot)

def addLineXY(lines, xvals, yvals, leg):
    new_line = {"xvals": xvals, "yvals": yvals, "legend_title": leg}
    lines.append(new_line)

def autolabel(rects):
    # attach some text labels
    for rect in rects:
        height = rect.get_height()
        plt.text(rect.get_x()+rect.get_width()/2.0, 1.01*height, '%.02f'%float(height), ha='center', va='bottom')

def main():

    plots = list()

    for m in models:
    
        time_lines = list()
        speedup_lines = list()
        efficiency_lines = list()
        memory_lines = list()
        premote_lines = list()
        rollback_lines = list()
        event_rate_lines = list()

        for cm in comm_models:

            nodes_x = list()
            time_y = list()
            speedup_y = list()
            comm_y = list()
            proc_y = list()
            memory_y = list()
            local_y = list()
            remote_y = list()
            prb_y = list()
            srb_y = list()

            single_node_time = 0;

            f = filenames(cm)
            for filename in f:
                # obtain configs from filename
                nodes, wt, sq, ssp, gvtp = re.findall(r'\d+', filename)

                with open("{}/{}/{}/{}".format(warped_data_path, m, cm, filename)) as plotpoint:
                    ydata = np.genfromtxt(filter_total_lines(plotpoint), delimiter=",",
                        names=['node', 'time', 'objects', 'localp', 'remotep', 'localn', 'remoten',
                               'prollbacks', 'srollbacks', 'coasted','cancelled', 'processed',
                               'committed', 'memory'])

                if nodes == '1':
                    single_node_time = np.mean(ydata['time'])

                nodes_x.append(nodes)
                time_y.append(np.mean(ydata['time']))
                comm_y.append(np.mean(ydata['committed']))
                proc_y.append(np.mean(ydata['processed']))
                memory_y.append(np.mean(ydata['memory']))
                local_y.append(np.mean(ydata['localp'])+np.mean(ydata['localn']))
                remote_y.append(np.mean(ydata['remotep'])+np.mean(ydata['remoten']))
                prb_y.append(np.mean(ydata['prollbacks']))
                srb_y.append(np.mean(ydata['srollbacks']))

            speedup = [single_node_time / a for a in time_y]
            efficiency = [a / b * 100 for a, b in zip(comm_y, proc_y)]
            premote = [a / (a + b) * 100 for a, b in zip(remote_y, local_y)]
            rollbacks = [(a + b) for a, b in zip(prb_y, srb_y)]
            event_rate = [a / b for a, b in zip(comm_y, time_y)]

#            addLineXY(time_lines, nodes_x, time_y, cm)
#            addLineXY(speedup_lines, nodes_x, speedup, cm)
            addLineXY(efficiency_lines, nodes_x, efficiency, cm)
#            addLineXY(memory_lines, nodes_x, memory_y, cm)
#            addLineXY(premote_lines, nodes_x, premote, cm)
#            addLineXY(rollback_lines, nodes_x, rollbacks, cm)
            addLineXY(event_rate_lines, nodes_x, event_rate, cm)

#        addPlotXY(plots, "{}".format(m), "# Nodes", "Simulation Time (s)", time_lines)
#        addPlotXY(plots, "{}".format(m), "# Nodes", "Speedup", speedup_lines)
        addPlotXY(plots, "{}".format(m), "# Nodes", "Efficiency (%)", efficiency_lines)
#        addPlotXY(plots, "{}".format(m), "# Nodes", "Memory", memory_lines)
#        addPlotXY(plots, "{}".format(m), "# Nodes", "% Remote", premote_lines)
#        addPlotXY(plots, "{}".format(m), "# Nodes", "Total Rollbacks", rollback_lines)
        addPlotXY(plots, "{}".format(m), "# Nodes", "Event Rate", event_rate_lines)

    for i, p in enumerate(plots):
        fig = plt.figure(i)
        plt.title(p["title"])
        plt.xlabel(p["xlabel"], fontsize=20)
        plt.ylabel(p["ylabel"], fontsize=20)
        
        legend_entries = list()
        for l in p["lines"]:
            plt.plot(l["xvals"], l["yvals"], marker='o')
            legend_entries.append(l["legend_title"])

        plt.grid()
        plt.legend(legend_entries, loc='upper center', bbox_to_anchor=(0.5, 1.10), ncol=4, fancybox=True, shadow=True)

    plt.show()

if __name__ == '__main__':
    main()


