PX=pdflatex

presentation: presentation.tex setup.sty
	$(PX) presentation.tex
	$(PX) presentation.tex

.PHONY: clean

clean:
	rm -f presentation.out presentation.aux presentation.toc presentation.nav presentation.log presentation.snm presentation.pdf
