#!/usr/bin/perl -w

use strict;

my $hostfile = "/home/weberd6/mpi_hosts";
my $mpirun_options = "-hostfile $hostfile -map-by node -bind-to none";
my $simulation_type = "time-warp";
my $model_path = "/home/weberd6/warped2-models/models/";
my $runs_per_cfg = 5;

my @model = ("pcs", "traffic", "epidemic");
my @max_aggregate = (1, 5, 10, 20, 30, 40, 50, 60, 70, 80);

my %max_sim_time = (
    "pcs"       => 10_000,
    "traffic"   => 100_000,
    "epidemic"  => 100_000,
    "airport"   => 100_000,
);

my $gvtperiod = 1000;
my $ss_period = 25;
my $wt = 7;
my $sq = 7;
my $partitioning_type = "round-robin";
my $pt = "block";
my $processes = 8;

sub run() {

    my @run_queue;

    for my $model (@model) {
        my $model_run = "$model_path"."$model/$model"."_sim";
        my $partitioning_file = "$model_path"."$model/statistics.out";
        my $model_options = "";

        my $max_sim_time = $max_sim_time{$model};

        foreach my $max_aggregate (@max_aggregate) {

            my $output_file = "$model/".
                              "${processes}n${wt}wt${sq}sq".
                              "${ss_period}ssp${gvtperiod}gvtp${max_aggregate}agg_${pt}.csv";

            my $kernel_run = "--max-sim-time $max_sim_time ".
                             "--simulation-type $simulation_type ".
                             "--time-warp-worker-threads $wt ".
                             "--time-warp-scheduler-count $sq ".
                             "--time-warp-lp-migration off ".
                             "--time-warp-state-saving-period $ss_period ".
                             "--partitioning-type $partitioning_type ".
                             "--partitioning-file $partitioning_file ".
                             "--time-warp-statistics-file $output_file ".
                             "--time-warp-gvt-calculation-period $gvtperiod ".
                             "--time-warp-config-output-file none ".
                             "--time-warp-communication-max-msg-size 512 ".
                             "--time-warp-communication-max-aggregate $max_aggregate";

            my $run = "/usr/local/mpich2/bin/mpirun -n $processes $mpirun_options $model_run $model_options $kernel_run";

            foreach (1..$runs_per_cfg) {
                push @run_queue, $run;
            }
        }
    }

    my $num_runs = @run_queue;
    my $i = 0;

    foreach (@run_queue) {
        ++$i;
        print "$i/$num_runs\n";
        next if $i <= 100;
        print "$_\n";
        my $output = `$_`;
        my @lines = split("\n", $output);
        for (@lines) {
            print "$_\n\n" if /Simulation completed in/;
        }
        sleep 10;
    }
}

run();

